import { Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

import Layout from "../components/organisms/Layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
